return {
    "simrat39/symbols-outline.nvim",
    config = function()
        require("symbols-outline").setup {
            highlight_hovered_item = true,
            show_guides = false,
            auto_preview = false,
            position = 'right',
            relative_width = true,
            width = 45,
            auto_close = true,
            show_numbers = false,
            show_relative_numbers = false,
            show_symbol_details = true,
            preview_bg_highlight = 'Pmenu',
            autofold_depth = nil,
            auto_unfold_hover = true,
            fold_markers = { '', '' },
            wrap = false,
            keymaps = {
                close = "q",
                code_actions = "<space>a",
                focus_location = "o",
                fold = "zc",
                fold_all = "zM",
                goto_location = "<CR>",
                hover_symbol = "<space>h",
                rename_symbol = "<space>r",
                unfold = "zo",
                unfold_all = "zR"
            },
            lsp_blacklist = {},
            symbol_blacklist = {},
            symbols = {
                Array = { hl = "TSConstant", icon = "" },
                Boolean = { hl = "TSBoolean", icon = "" },
                Class = { hl = "TSType", icon = "" },
                Constant = { hl = "TSConstant", icon = "" },
                Constructor = { hl = "TSConstructor", icon = "" },
                Enum = { hl = "TSType", icon = "" },
                EnumMember = { hl = "TSField", icon = "" },
                Event = { hl = "TSType", icon = "" },
                Field = { hl = "TSField", icon = "" },
                File = { hl = "TSURI", icon = "" },
                Function = { hl = "TSFunction", icon = "" },
                Interface = { hl = "TSType", icon = "" },
                Key = { hl = "TSType", icon = " " },
                Method = { hl = "TSMethod", icon = "" },
                Module = { hl = "TSNamespace", icon = "" },
                Namespace = { hl = "TSNamespace", icon = "" },
                Null = { hl = "TSType", icon = "" },
                Number = { hl = "TSNumber", icon = "" },
                Object = { hl = "TSType", icon = "" },
                Operator = { hl = "TSOperator", icon = "" },
                Package = { hl = "TSNamespace", icon = "" },
                Property = { hl = "TSMethod", icon = "" },
                String = { hl = "TSString", icon = "" },
                Struct = { hl = "TSType", icon = "" },
                TypeParameter = { hl = "TSParameter", icon = "" },
                Variable = { hl = "TSConstant", icon = "" }
            },
        }
        vim.keymap.set('n', "<F2>", ":SymbolsOutline<CR>")
    end

}
